export type SupportedLocale = 'en-US' | 'th' | 'vi-VN' | 'zh-CN' | 'zh-TW'
export const isSupportedLocale = (locale: string) => {
    return ['en-US', 'th', 'vi-VN', 'zh-CN', 'zh-TW'].includes(locale);
}
export const getLocalizedKeyword = (locale: SupportedLocale) => {
    const metadata = {
        'en-US': [
            "Ambush Opportunity",
            "Online trading platform",
            "CFD trading",
            "CFD",
            "Online Trading",
            "Free demo account",
            "Open account",
            "Online register",
            "Margin",
            "Leverage",
            "MetaTrader 4 (MT4)",
            "Deposit USDT",
            "Withdraw USDT",
            "invest",
            "Currency pair",
            "Forex CFDs",
            "Indices CFDs",
            "Precious Metals CFDs",
            "Energy CFDs",
            "Cryptocurrency CFDs",
            "NFP",
            "CPI",
            "PPI",
            "inflation",
            "UI Claims",
            "Retail Sales",
            "EIA crude oil inventories",
            "unemployment rate",
            "iExposure",
            "MACD",
            "Momentum",
            "OsMa",
            "ZigZag",
            "Accelerator Oscillator",
            "Accumulation/Distribution",
            "Average directional movement index",
            "Average true range",
            "Awesome Oscillator",
            "Envelopes",
            "Ichimoku Kinko Hyo",
            "Parabolic SAR",
            "Standard deviation",
            "Commodity channel index",
            "DeMarker",
            "Relative strength index",
            "Relative vigor index",
            "Stochastic Oscillator",
            "Williams' percent range",
            "Money flow index",
            "On balance volume",
            "Volumes",
            "Fractals",
            "Gator Oscillator",
            "Market Faciliation index",
            "indicator",
            "band",
            "fibonacci",
            "RSI",
            "MA",
            "Moving Average",
            "stop loss/SL",
            "consumer confidence",
            "take profit/TP",
            "buy stop",
            "sell stop",
            "buy limit",
            "sell limit",
            "hedging",
            "scalping",
            "EA",
            "manual trading",
            "economic calendar",
            "swap",
            "spread/pip",
            "analysis",
            "PTips",
            "forex news",
            "best forext broker",
            "trading account",
            "Forex trading strategies",
            "Forex education",
            "liquidity"
        ],
        'vi-VN': [
            "Ambush Opportunity",
            "Nền tảng giao dịch trực tuyến",
            "Giao dịch CFD",
            "CFD",
            "Giao dịch trực tuyến",
            "Tài khoản Demo miễn phí",
            "Mở tài khoản",
            "Đăng ký trực tuyến",
            "Ký quỹ",
            "Đòn bẩy",
            "MetaTrader 4 (MT4)",
            "Gửi tiền USDT",
            "Rút tiền USDT",
            "Đầu tư",
            "Cặp tiền tệ",
            "Giao dịch ngoại hối CFDs",
            "giao dịch chỉ số CFDs",
            "Giao dịch kim loại quý CFDs",
            "Giao dịch năng lượng CFDs",
            "Giao dịch tiền điện tử CFDs",
            "Giao dịch báo cáo lương phi nông nghiệp (non-farm)",
            "Quyết định lãi suất",
            "Chỉ số giá sản xuất",
            "Lạm phát",
            "Đề nghị trợ cấp thất nghiệp lần đầu",
            "Tỉ lệ bán lẻ hàng tháng",
            "Tồn kho dầu thô EIA",
            "Tỉ lệ thất nghiệp",
            "iExposure",
            "MACD",
            "Chỉ báo động lượng",
            "Dao động trung bình di chuyển",
            "Chỉ báo zigzag",
            "Dao động gia tốc",
            "Tích lũy/Phân phối",
            "Chỉ số định hướng trung bình",
            "Phạm vi thực trung bình",
            "Awesome Oscillator",
            "Envelopes",
            "Sơ đồ cân bằng Ichimoku",
            "Parabolic SAR",
            "Độ lệch chuẩn",
            "Chỉ số kênh hàng hóa",
            "DeMarker",
            "Chỉ báo sức mạnh tương đối (RSI)",
            "Chỉ báo sức sống tương đối (RVI)",
            "Stochastic Oscillator",
            "Chỉ báo Williams %R",
            "Chỉ báo dòng tiền",
            "Chỉ báo cân bằng khối lượng (OBV)",
            "Khối lượng",
            "Chỉ báo Fractals",
            "Gator Oscillator",
            "Chỉ số khối lượng tài sản giao dịch",
            "Chỉ báo (indicator)",
            "dải",
            "fibonacci",
            "RSI",
            "đường MA",
            "Đường trung bình động",
            "Cắt lỗ (SL)",
            "Chỉ số niềm tin người tiêu dùng",
            "Chốt lời (TP)",
            "buy stop",
            "sell stop",
            "buy limit",
            "sell limit",
            "Phòng vệ giá (hedging)",
            "Lướt sóng (Scalping)",
            "Giao dịch tự động EA",
            "Giao dịch thủ công",
            "Lịch kinh tế",
            "Phí qua đêm",
            "spread/pip",
            "Phân tích",
            "PTips",
            "Tin tức ngoại hối",
            "Sàn giao dịch tốt nhất",
            "Tài khoản giao dịch",
            "Chiến lược giao dịch ngoại hối",
            "Đào tạo ngoại hối",
            "Tính thanh khoản"
        ],
        'th': [
            "Ambush Opportunity",
            "แพลตฟอร์มการซื้อขายออนไลน์",
            "การซื้อขาย CFD",
            "CFD",
            "การซื้อขายออนไลน์",
            "บัญชีทดลองฟรี",
            "เปิดบัญชี",
            "ลงทะเบียนออนไลน์",
            "หลักประกัน",
            "เลเวอเรจ",
            "MetaTrader 4 (MT4)",
            "ฝากเงิน USDT",
            "ถอนเงิน USDT",
            "ลงทุน",
            "คู่สกุลเงิน",
            "ฟอเร็กซ์ CFD",
            "ดัชนี CFD",
            "โลหะมีค่า CFD",
            "พลังงาน CFD",
            "สกุลเงินดิจิทัล CFD",
            "เอ็นเอฟพี",
            "ดัชนีราคาผู้บริโภค",
            "พีพีไอ",
            "เงินเฟ้อ",
            "UI Claims",
            "ยอดค้าปลีก",
            "EIA สินค้าคงคลังน้ำมันดิบ",
            "อัตราการว่างงาน",
            "iExposure",
            "MACD",
            "โมเมนตัม",
            "ออสมา",
            "ซิกแซก",
            "Accelerator Oscillator",
            "การสะสม/การกระจาย",
            "ดัชนีการเคลื่อนที่ทิศทางเฉลี่ย",
            "ช่วงที่แท้จริงเฉลี่ย",
            "Awesome Oscillator",
            "ซองจดหมาย",
            "อิจิโมกุ คินโกะ ฮโย",
            "Parabolic SAR",
            "ส่วนเบี่ยงเบนมาตรฐาน",
            "ดัชนีช่องทางสินค้าโภคภัณฑ์",
            "DeMarker",
            "Relative strength index",
            "Relative vigor index",
            "Stochastic Oscillator",
            "Williams' percent range",
            "ดัชนีการไหลของเงิน",
            "เกี่ยวกับปริมาณความสมดุล",
            "ปริมาณ",
            "Fractals",
            "Gator Oscillator",
            "ดัชนีการอำนวยความสะดวกทางการตลาด",
            "เครื่องมือบ่งชี้ (indicator)",
            "band",
            "fibonacci",
            "RSI",
            "MA",
            "Moving Average",
            "จุดหยุดขาดทุน/SL",
            "ความเชื่อมั่นของผู้บริโภค",
            "จุดทำกำไร/TP",
            "buy stop",
            "sell stop",
            "buy limit",
            "sell limit",
            "การบริหารจัดการความเสี่ยงที่ชดเชยภาวะขาดทุนที่อาจเกิดขึ้นได้โดยการเปิดสถานะตรงกันข้าม",
            "การเทรดที่ใช้กลยุทธ์การเทรดระยะสั้น (scalping)",
            "EA",
            "การซื้อขายด้วยตนเอง",
            "ปฏิทินเศรษฐกิจ",
            "ค่าธรรมเนียมการถือสถานะข้ามคืน",
            "ค่าธรรมเนียม/pip",
            "การวิเคราะห์",
            "PTips",
            "ข่าวฟอเร็กซ์",
            "โบรกเกอร์ฟอเร็กซ์ที่ดีที่สุด",
            "บัญชีซื้อขาย",
            "กลยุทธ์การเทรดฟอเร็กซ์",
            "สอนเทรดฟอเร็กซ์",
            "สภาพคล่อง"
        ],
        'zh-TW': [
            "寶泰",
            "Ambush Opportunity",
            "網上交易平臺",
            "CFD 交易",
            "差價合約",
            "在線交易",
            "免費模擬帳戶",
            "開戶",
            "線上開戶",
            "保證金",
            "槓桿",
            "MetaTrader 4 (MT4)",
            "USDT入金",
            "USDT出金",
            "投資",
            "貨幣對",
            "外匯交易",
            "指數交易",
            "貴金屬交易",
            "能源交易",
            "數字貨幣交易",
            "非農",
            "利率決議",
            "生產物價指數",
            "通膨",
            "初請失業金人數",
            "零售銷售月率",
            "EIA原油庫存",
            "失業率",
            "曝露指標",
            "MACD",
            "動量指標",
            "移動平均震盪指標",
            "之字轉向指標",
            "加速震盪指標",
            "累積/派發指標",
            "平均方向指標",
            "平均真實範圍",
            "超級震盪指標",
            "包絡線指標",
            "一目均衡圖",
            "拋物線指標",
            "標準差",
            "商品通道指標",
            "德馬克指標",
            "相對強弱指標",
            "相對活力指標",
            "隨機指標",
            "威廉指標",
            "資金流量指標",
            "能量潮指標",
            "成交量指標",
            "分形指標",
            "鱷魚震盪指標",
            "市場促進指標",
            "指標",
            "布林",
            "斐波納奇",
            "相對強弱指數",
            "MA線",
            "移動平均線",
            "止損",
            "消費者信心指數",
            "止盈",
            "止損買入",
            "止損賣出",
            "限價買入",
            "限價賣出",
            "對沖",
            "剝頭皮",
            "自動交易",
            "手動交易",
            "經濟週報",
            "隔夜利息",
            "點差",
            "技術分析",
            "指標教學",
            "外匯新聞",
            "最佳外匯經紀商",
            "交易帳戶",
            "外匯交易策略",
            "外匯教育",
            "流動性"
        ],
        'zh-CN': [
            "宝泰",
            "Ambush Opportunity",
            "网上交易平台",
            "CFD 交易",
            "差价合约",
            "在线交易",
            "免费模拟账户",
            "开户",
            "在线开户",
            "保证金",
            "杠杆",
            "MetaTrader 4 (MT4)",
            "USDT入金",
            "USDT出金",
            "投资",
            "货币对",
            "外汇交易",
            "指数交易",
            "贵金属交易",
            "能源交易",
            "数字货币交易",
            "非农",
            "利率决议",
            "生产物价指数",
            "通膨",
            "初请失业金人数",
            "零售销售月率",
            "EIA原油库存",
            "失业率",
            "曝露指标",
            "MACD",
            "动量指标",
            "移动平均震荡指针",
            "之字转向指标",
            "加速震荡指标",
            "累积/派发指标",
            "平均方向指针",
            "平均真实范围",
            "超级震荡指标",
            "包络线指标",
            "一目均衡图",
            "抛物线指标",
            "标准偏差",
            "商品通道指针",
            "德马克指标",
            "相对强弱指标",
            "相对活力指标",
            "随机指标",
            "威廉指标",
            "资金流量指标",
            "能量潮指标",
            "成交量指标",
            "分形指标",
            "鳄鱼震荡指标",
            "市场促进指标",
            "指标",
            "布林",
            "斐波纳奇",
            "相对强弱指数",
            "MA线",
            "移动平均线",
            "止损",
            "消费者信心指数",
            "止盈",
            "止损买入",
            "止损卖出",
            "限价买入",
            "限价卖出",
            "对冲",
            "剥头皮",
            "自动交易",
            "手动交易",
            "经济周报",
            "隔夜利息",
            "点差",
            "技术分析",
            "指标教学",
            "外汇新闻",
            "最佳外汇经纪商",
            "交易账户",
            "外汇交易策略",
            "外汇教育",
            "流动性"
        ]
    };

    return metadata[locale] || metadata["en-US"];
};
